// Curated 5-letter Arabic vocabulary for the lesson game.
// Spelling is normalized for tile play: plain ا for hamza variants, no ى.
// Every letter used here appears on the in-game Arabic keyboard.

export interface ArabicWord {
  word: string;
  translit: string;
  meaning: string;
}

export const ARABIC_WORDS: ArabicWord[] = [
  { word: "مدرسة", translit: "madrasa", meaning: "school" },
  { word: "مكتبة", translit: "maktaba", meaning: "library" },
  { word: "سيارة", translit: "sayyara", meaning: "car" },
  { word: "حديقة", translit: "hadiqa", meaning: "garden" },
  { word: "جزيرة", translit: "jazira", meaning: "island" },
  { word: "طاولة", translit: "tawila", meaning: "table" },
  { word: "نافذة", translit: "nafidha", meaning: "window" },
  { word: "مفتاح", translit: "miftah", meaning: "key" },
  { word: "قاموس", translit: "qamus", meaning: "dictionary" },
  { word: "صديقة", translit: "sadiqa", meaning: "friend (female)" },
  { word: "مدينة", translit: "madina", meaning: "city" },
  { word: "رسالة", translit: "risala", meaning: "message, letter" },
  { word: "جريدة", translit: "jarida", meaning: "newspaper" },
  { word: "دراجة", translit: "darraja", meaning: "bicycle" },
  { word: "حقيبة", translit: "haqiba", meaning: "bag" },
  { word: "دقيقة", translit: "daqiqa", meaning: "minute" },
  { word: "ثلاجة", translit: "thallaja", meaning: "refrigerator" },
  { word: "ملعقة", translit: "mil'aqa", meaning: "spoon" },
  { word: "تفاحة", translit: "tuffaha", meaning: "apple" },
  { word: "بطيخة", translit: "battikha", meaning: "watermelon" },
  { word: "طماطم", translit: "tamatim", meaning: "tomatoes" },
  { word: "خيارة", translit: "khiyara", meaning: "cucumber" },
  { word: "ليمون", translit: "laymun", meaning: "lemon" },
  { word: "دجاجة", translit: "dajaja", meaning: "chicken" },
  { word: "معلمة", translit: "mu'allima", meaning: "teacher (female)" },
  { word: "طبيبة", translit: "tabiba", meaning: "doctor (female)" },
  { word: "مهندس", translit: "muhandis", meaning: "engineer" },
  { word: "مزارع", translit: "muzari'", meaning: "farmer" },
  { word: "طالبة", translit: "taliba", meaning: "student (female)" },
  { word: "والدة", translit: "walida", meaning: "mother" },
  { word: "حبيبة", translit: "habiba", meaning: "sweetheart (female)" },
  { word: "غزالة", translit: "ghazala", meaning: "gazelle" },
  { word: "زرافة", translit: "zarafa", meaning: "giraffe" },
  { word: "عصفور", translit: "'usfur", meaning: "small bird" },
  { word: "فراشة", translit: "farasha", meaning: "butterfly" },
  { word: "تمساح", translit: "timsah", meaning: "crocodile" },
  { word: "مصباح", translit: "misbah", meaning: "lamp" },
  { word: "خزانة", translit: "khizana", meaning: "closet" },
  { word: "وسادة", translit: "wisada", meaning: "pillow" },
  { word: "صابون", translit: "sabun", meaning: "soap" },
  { word: "منشفة", translit: "minshafa", meaning: "towel" },
  { word: "فرشاة", translit: "furshah", meaning: "brush" },
  { word: "معجون", translit: "ma'jun", meaning: "toothpaste" },
  { word: "ملابس", translit: "malabis", meaning: "clothes" },
  { word: "بنطال", translit: "bantal", meaning: "trousers" },
  { word: "فستان", translit: "fustan", meaning: "dress" },
  { word: "جوارب", translit: "jawarib", meaning: "socks" },
  { word: "نظارة", translit: "nazzara", meaning: "eyeglasses" },
  { word: "محفظة", translit: "mihfaza", meaning: "wallet" },
  { word: "حاسوب", translit: "hasub", meaning: "computer" },
  { word: "طابعة", translit: "tabi'a", meaning: "printer" },
  { word: "تلفاز", translit: "tilfaz", meaning: "television" },
  { word: "مذياع", translit: "midhya'", meaning: "radio" },
  { word: "كتابة", translit: "kitaba", meaning: "writing" },
  { word: "قصيدة", translit: "qasida", meaning: "poem" },
  { word: "رواية", translit: "riwaya", meaning: "novel" },
  { word: "اغنية", translit: "ughniya", meaning: "song" },
  { word: "رياضة", translit: "riyada", meaning: "sport" },
  { word: "سباحة", translit: "sibaha", meaning: "swimming" },
  { word: "سفينة", translit: "safina", meaning: "ship" },
  { word: "حافلة", translit: "hafila", meaning: "bus" },
  { word: "اجازة", translit: "ijaza", meaning: "holiday, vacation" },
  { word: "بحيرة", translit: "buhayra", meaning: "lake" },
  { word: "طبيعة", translit: "tabi'a", meaning: "nature" },
  { word: "مزرعة", translit: "mazra'a", meaning: "farm" },
  { word: "سحابة", translit: "sahaba", meaning: "cloud" },
  { word: "عاصفة", translit: "'asifa", meaning: "storm" },
  { word: "امطار", translit: "amtar", meaning: "rain" },
  { word: "حرارة", translit: "harara", meaning: "heat" },
  { word: "تاريخ", translit: "tarikh", meaning: "history, date" },
  { word: "وظيفة", translit: "wazifa", meaning: "job" },
  { word: "سعادة", translit: "sa'ada", meaning: "happiness" },
  { word: "صداقة", translit: "sadaqa", meaning: "friendship" },
  { word: "اسبوع", translit: "usbu'", meaning: "week" },
];
